/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as NewsRouteImport } from './routes/news';
import { Route as FavoritesRouteImport } from './routes/favorites';
import { Route as DeliveryRouteImport } from './routes/delivery';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as CatalogRouteImport } from './routes/catalog';
import { Route as AccountRouteImport } from './routes/account';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ProductIdRouteImport } from './routes/product.$id';
const PrivacyRoute = PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => rootRouteImport,
});
const NewsRoute = NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => rootRouteImport,
});
const FavoritesRoute = FavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => rootRouteImport,
});
const DeliveryRoute = DeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const CheckoutRoute = CheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => rootRouteImport,
});
const CatalogRoute = CatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => rootRouteImport,
});
const AccountRoute = AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ProductIdRoute = ProductIdRouteImport.update({
    id: '/product/$id',
    path: '/product/$id',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    AccountRoute: AccountRoute,
    CatalogRoute: CatalogRoute,
    CheckoutRoute: CheckoutRoute,
    ContactRoute: ContactRoute,
    DeliveryRoute: DeliveryRoute,
    FavoritesRoute: FavoritesRoute,
    NewsRoute: NewsRoute,
    PrivacyRoute: PrivacyRoute,
    ProductIdRoute: ProductIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
